import React from 'react';
import Svg, { Path } from 'react-native-svg';
import {
  MagnifyingGlass,
  House,
  Key,
  SquaresFour,
  List,
  Bell,
  Moon,
  CaretLeft,
  CaretRight,
  CaretDown,
  X,
  Heart,
  DotsThreeVertical,
  Trash,
  Calendar,
  Sparkle,
  Wrench,
  ClipboardText,
  ChatCircle,
  Ticket,
  Siren,
  Package,
  Handshake,
  Shield,
  User,
  Users,
  UserPlus,
  CreditCard,
  Gear,
  Globe,
  Check,
  CalendarPlus,
  QrCode,
  Buildings,
  Bed,
  Bathtub,
  Stairs,
  FrameCorners,
  Camera,
  Coins,
  MapPin,
  NotePencil,
  WarningCircle,
  Envelope,
  Phone,
  GoogleLogo,
  FacebookLogo,
  AppleLogo,
  ArrowsLeftRight,
  Funnel,
  LockSimple,
  Plus,
  Couch,
  Armchair,
  Snowflake,
  Fan,
  Television,
  Desk,
  Chair,
  CookingPot,
  Oven,
  WashingMachine,
  Drop,
  Car,
  Motorcycle,
  Bicycle,
  Waves,
  Barbell,
  Tree,
  PawPrint,
  WifiHigh,
  FireExtinguisher,
  Broom,
  Archive,
  Plug,
  Lightning,
  Bus,
  Train,
  Park,
  Flame,
  CoatHanger,
  Door,
  SwimmingPool,
  Plant,
  Cube,
  Garage,
  ChargingStation,
  Shower,
  ForkKnife,
  Wine,
  Toilet,
  Thermometer,
  Wind,
  Elevator,
  IconProps,
} from 'phosphor-react-native';
import { tokens } from '../theme/tokens';
import { AppIconName, AppIconTone } from './types';

const ICON_MAP: Record<Exclude<AppIconName, 'house-plus'>, React.ComponentType<IconProps>> = {
  search: MagnifyingGlass,
  home: House,
  key: Key,
  grid: SquaresFour,
  'list-rows': List,
  menu: List,
  bell: Bell,
  moon: Moon,
  'chevron-left': CaretLeft,
  'chevron-right': CaretRight,
  'chevron-down': CaretDown,
  close: X,
  heart: Heart,
  'dots-vertical': DotsThreeVertical,
  trash: Trash,
  calendar: Calendar,
  sparkle: Sparkle,
  wrench: Wrench,
  clipboard: ClipboardText,
  chat: ChatCircle,
  ticket: Ticket,
  siren: Siren,
  package: Package,
  handshake: Handshake,
  shield: Shield,
  user: User,
  users: Users,
  'user-plus': UserPlus,
  'credit-card': CreditCard,
  gear: Gear,
  globe: Globe,
  check: Check,
  'calendar-plus': CalendarPlus,
  'qr-code': QrCode,
  buildings: Buildings,
  bed: Bed,
  bath: Bathtub,
  stairs: Stairs,
  'room-size': FrameCorners,
  camera: Camera,
  coins: Coins,
  'map-pin': MapPin,
  note: NotePencil,
  warning: WarningCircle,
  envelope: Envelope,
  phone: Phone,
  google: GoogleLogo,
  facebook: FacebookLogo,
  apple: AppleLogo,
  swap: ArrowsLeftRight,
  funnel: Funnel,
  lock: LockSimple,
  plus: Plus,
  couch: Couch,
  armchair: Armchair,
  snowflake: Snowflake,
  fan: Fan,
  television: Television,
  desk: Desk,
  chair: Chair,
  'cooking-pot': CookingPot,
  oven: Oven,
  'washing-machine': WashingMachine,
  drop: Drop,
  car: Car,
  motorcycle: Motorcycle,
  bicycle: Bicycle,
  waves: Waves,
  barbell: Barbell,
  tree: Tree,
  paw: PawPrint,
  wifi: WifiHigh,
  'fire-extinguisher': FireExtinguisher,
  broom: Broom,
  archive: Archive,
  plug: Plug,
  lightning: Lightning,
  bus: Bus,
  train: Train,
  park: Park,
  flame: Flame,
  'coat-hanger': CoatHanger,
  door: Door,
  'swimming-pool': SwimmingPool,
  plant: Plant,
  cube: Cube,
  garage: Garage,
  'charging-station': ChargingStation,
  shower: Shower,
  'fork-knife': ForkKnife,
  wine: Wine,
  toilet: Toilet,
  thermometer: Thermometer,
  wind: Wind,
  elevator: Elevator,
};

const TONE_COLORS: Record<AppIconTone, string> = {
  active: tokens.colors.icon.dark,
  inactive: tokens.colors.icon.secondary,
  brand: tokens.colors.icon.brand,
  white: tokens.colors.icon.white,
  muted: tokens.colors.icon.muted,
  danger: tokens.colors.danger,
  accent: tokens.colors.accent,
  success: tokens.colors.success,
  warning: tokens.colors.warning,
};

export interface MobileIconProps {
  name: AppIconName;
  size?: number;
  tone?: AppIconTone;
  color?: string;
  weight?: IconProps['weight'];
}

export const MobileIcon: React.FC<MobileIconProps> = ({
  name,
  size = 22,
  tone = 'inactive',
  color,
  weight = 'regular',
}) => {
  if (name === 'house-plus') {
    return (
      <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" accessible={false}>
        <Path
          d="M12 20H3V10L12 2L20 9M19 13V21M15 17H23"
          stroke={color ?? TONE_COLORS[tone]}
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </Svg>
    );
  }
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return <Icon size={size} color={color ?? TONE_COLORS[tone]} weight={weight} />;
};
