import type { SupportedLocale } from "@nestyk/i18n";

const copy = {
  th: {
    latest: "ล่าสุด",
    paid: "ชำระแล้ว",
    billDetails: "รายละเอียดบิล",
    currentBill: "บิลปัจจุบัน",
    billNo: "เลขที่บิล",
    billsList: "รายการบิล",
    allBills: "ทั้งหมด",
    unpaid: "ยังไม่ชำระ",
    pay: "แจ้งชำระเงิน / แนบสลิป",
    reviewing: "รอตรวจสอบ",
    copyAccount: "คัดลอก",
    copied: "คัดลอกแล้ว",
    copyFailed: "คัดลอกเลขบัญชีไม่สำเร็จ กรุณาลองอีกครั้ง",
    room: "ห้อง",
    unitNo: "เลขที่",
    noPaidBills: "ยังไม่มีบิลที่ชำระแล้ว",
    noUnpaidBills: "ยังไม่มีบิลที่ยังไม่ชำระ",
    noBills: "ยังไม่มีรายการบิล",
    myContracts: "สัญญาของฉัน",
    contractsAndTenants: "สัญญาและผู้เช่า",
    ownerWorkspace: "เจ้าของ",
    searchRooms: "ค้นหาห้อง",
    allRooms: "ทุกห้อง",
    waitingOnYou: "รอคุณดำเนินการ",
    roomsWithContracts: "ห้องของคุณ",
    roomCount: "{count} ห้อง",
    noLeaseHistory: "ยังไม่มีประวัติการเช่า",
    leaseRounds: "ประวัติ {count} รอบ",
    pendingDocs: "{count} เอกสารค้าง",
    waitingYourSignature: "รอคุณลงนาม",
    awaitingAgentSignature: "รอนายหน้าลงนาม",
    noActiveContract: "ไม่มีสัญญาใช้งาน",
    renewalAction: "ต่อสัญญา",
    clearSearch: "ล้างคำค้น",
    noMatchingRooms: "ไม่พบห้องที่ตรงกับคำค้น",
    roomHistory: "ห้องที่เคยอยู่",
    leasedRooms: "ห้องที่เคยปล่อย",
    emptyLeasedRooms: "ยังไม่มีห้องที่เคยปล่อย",
    tenantHistory: "ประวัติผู้เช่าทั้งหมด",
    tenantHistoryHint: "เปิดชื่อเพื่อดูสัญญาของผู้เช่านั้น",
    searchTenants: "ค้นหาผู้เช่า",
    noMatchingTenants: "ไม่พบผู้เช่าที่ตรงกับคำค้น",
    emptyTenantHistory: "ยังไม่มีประวัติผู้เช่า",
    noCurrentTenant: "ยังไม่มีผู้เช่าปัจจุบัน",
    roomTenants: "ผู้ที่เคยเช่าห้องนี้",
    emptyRoomTenants: "ยังไม่มีผู้เช่าในห้องนี้",
    peopleCount: "{count} คน",
    stayDates: "เข้า {moveIn} · ออก {moveOut}",
    roomHistoryHint: "เปิดห้องเพื่อดูสัญญาและเอกสาร",
    billHistoryHint: "เปิดห้องเพื่อดูบิลของห้องนั้น",
    paymentHistory: "ประวัติการจ่าย",
    billCount: "{count} บิล",
    currentStay: "อยู่ปัจจุบัน",
    pastStay: "ย้ายออกแล้ว",
    emptyHistory: "ยังไม่มีห้องที่เคยอยู่",
    currentContract: "สัญญาปัจจุบัน",
    nextRentBill: "บิลค่าห้องรอบถัดไป",
    noMoreRentBills: "ไม่มีบิลค่าห้องรอบถัดไปในสัญญานี้",
    lease: "สัญญาเช่าที่พักอาศัย",
    reservation: "หนังสือจอง",
    broker: "แต่งตั้งนายหน้า",
    contractNo: "เลขที่สัญญา",
    start: "เริ่มสัญญา",
    end: "สิ้นสุดสัญญา",
    rent: "ค่าเช่า / เดือน",
    deposit: "เงินประกัน",
    tenant: "ผู้เช่า",
    owner: "ผู้ให้เช่า",
    signed: "ลงนามแล้ว",
    unsigned: "ยังไม่ลงนาม",
    viewContract: "ดูสัญญา",
    viewAndSign: "ดูและลงนาม",
    roomDocuments: "เอกสารของห้องนี้",
    attachments: "เอกสารแนบท้ายสัญญา",
    documentHint: "ดูเอกสารที่แนบกับสัญญา",
    noAttachments: "ยังไม่มีเอกสารแนบท้ายสัญญา",
    contractCount: "{count} ฉบับ",
    contractsHint: "เปิดดูสำเนาสัญญาและตรวจสอบสถานะการลงนามได้ในที่เดียว",
    emptyContracts: "ยังไม่มีสัญญาที่ส่งเข้าบัญชีนี้",
    emptyRoom: "ไม่มีสัญญาในห้องนี้",
    status: {
      draft: "ฉบับร่าง",
      awaiting_signatures: "รอลงนาม",
      awaiting_agent_review: "รอตรวจสัญญา",
      awaiting_payment: "รอชำระเงิน",
      awaiting_payment_verification: "รอตรวจชำระเงิน",
      active: "มีผลแล้ว",
      cancelled: "ยกเลิก",
      expired: "หมดอายุ",
      terminated: "สิ้นสุดสัญญา",
    },
  },
  en: {
    latest: "Latest",
    paid: "Paid",
    billDetails: "Bill details",
    currentBill: "Current bill",
    billNo: "Bill no.",
    billsList: "Bills",
    allBills: "All",
    unpaid: "Unpaid",
    pay: "Report payment / attach slip",
    reviewing: "Under review",
    copyAccount: "Copy",
    copied: "Copied",
    copyFailed: "Could not copy the account number. Please try again.",
    room: "Room",
    unitNo: "No.",
    noPaidBills: "No paid bills yet",
    noUnpaidBills: "No unpaid bills",
    noBills: "No bills yet",
    myContracts: "My contracts",
    contractsAndTenants: "Contracts and tenants",
    ownerWorkspace: "Owner",
    searchRooms: "Search rooms",
    allRooms: "All rooms",
    waitingOnYou: "Waiting on you",
    roomsWithContracts: "Your rooms",
    roomCount: "{count} rooms",
    noLeaseHistory: "No past tenancies",
    leaseRounds: "{count} past stays",
    pendingDocs: "{count} documents open",
    waitingYourSignature: "Waiting for your signature",
    awaitingAgentSignature: "Waiting for the agent",
    noActiveContract: "No active contract",
    renewalAction: "Renewal",
    clearSearch: "Clear search",
    noMatchingRooms: "No rooms match your search",
    roomHistory: "Rooms I've stayed in",
    leasedRooms: "Rooms I've leased",
    emptyLeasedRooms: "No leased rooms yet",
    tenantHistory: "All tenant history",
    tenantHistoryHint: "Open a name to view that tenant's contracts",
    searchTenants: "Search tenants",
    noMatchingTenants: "No tenants match your search",
    emptyTenantHistory: "No tenant history yet",
    noCurrentTenant: "No current tenant",
    roomTenants: "People who stayed here",
    emptyRoomTenants: "No one has stayed in this room",
    peopleCount: "{count} people",
    stayDates: "In {moveIn} · Out {moveOut}",
    roomHistoryHint: "Open a room to view its contracts and documents",
    billHistoryHint: "Open a room to view its bills",
    paymentHistory: "Payment history",
    billCount: "{count} bills",
    currentStay: "Current stay",
    pastStay: "Moved out",
    emptyHistory: "No rooms yet",
    currentContract: "Current lease",
    nextRentBill: "Next rent bill",
    noMoreRentBills: "No further rent bills scheduled for this lease",
    lease: "Residential lease",
    reservation: "Reservation letter",
    broker: "Broker appointment",
    contractNo: "Contract no.",
    start: "Start date",
    end: "End date",
    rent: "Monthly rent",
    deposit: "Security deposit",
    tenant: "Tenant",
    owner: "Landlord",
    signed: "Signed",
    unsigned: "Not signed",
    viewContract: "View contract",
    viewAndSign: "Review and sign",
    roomDocuments: "Room documents",
    attachments: "Contract attachments",
    documentHint: "View documents attached to this contract",
    noAttachments: "No contract attachments yet",
    contractCount: "{count} contracts",
    contractsHint:
      "View your contract copies and signature status in one place.",
    emptyContracts: "No contracts delivered to this account yet",
    emptyRoom: "No contracts for this room",
    status: {
      draft: "Draft",
      awaiting_signatures: "Awaiting signatures",
      awaiting_agent_review: "Awaiting review",
      awaiting_payment: "Awaiting payment",
      awaiting_payment_verification: "Payment under review",
      active: "Active",
      cancelled: "Cancelled",
      expired: "Expired",
      terminated: "Terminated",
    },
  },
  zh: {
    latest: "最新",
    paid: "已付款",
    billDetails: "账单详情",
    currentBill: "当前账单",
    billNo: "账单编号",
    billsList: "账单列表",
    allBills: "全部",
    unpaid: "未付款",
    pay: "申报付款 / 上传凭证",
    reviewing: "审核中",
    copyAccount: "复制",
    copied: "已复制",
    copyFailed: "无法复制账号，请重试",
    room: "房间",
    unitNo: "编号",
    noPaidBills: "暂无已付款账单",
    noUnpaidBills: "暂无未付款账单",
    noBills: "暂无账单",
    myContracts: "我的合同",
    contractsAndTenants: "合同与租客",
    ownerWorkspace: "业主",
    searchRooms: "搜索房间",
    allRooms: "全部房间",
    waitingOnYou: "待你处理",
    roomsWithContracts: "您的房间",
    roomCount: "{count} 间",
    noLeaseHistory: "还没有租住记录",
    leaseRounds: "历史 {count} 次",
    pendingDocs: "{count} 份文件待处理",
    waitingYourSignature: "待你签署",
    awaitingAgentSignature: "待经纪人签署",
    noActiveContract: "没有生效中的合同",
    renewalAction: "续约",
    clearSearch: "清除搜索",
    noMatchingRooms: "没有符合搜索的房间",
    roomHistory: "住过的房间",
    leasedRooms: "曾出租的房间",
    emptyLeasedRooms: "还没有出租过的房间",
    tenantHistory: "全部租客记录",
    tenantHistoryHint: "打开姓名查看该租客的合同",
    searchTenants: "搜索租客",
    noMatchingTenants: "没有符合搜索的租客",
    emptyTenantHistory: "还没有租客记录",
    noCurrentTenant: "目前没有租客",
    roomTenants: "曾入住此房间的人",
    emptyRoomTenants: "此房间还没有租客",
    peopleCount: "{count} 人",
    stayDates: "入住 {moveIn} · 退房 {moveOut}",
    roomHistoryHint: "打开房间查看合同和文件",
    billHistoryHint: "打开房间查看账单",
    paymentHistory: "付款记录",
    billCount: "{count} 张账单",
    currentStay: "当前入住",
    pastStay: "已搬离",
    emptyHistory: "还没有住过的房间",
    currentContract: "当前租约",
    nextRentBill: "下期租金账单",
    noMoreRentBills: "此租约没有后续租金账单",
    lease: "住宅租赁合同",
    reservation: "预订书",
    broker: "经纪人委任书",
    contractNo: "合同编号",
    start: "开始日期",
    end: "结束日期",
    rent: "月租",
    deposit: "押金",
    tenant: "租客",
    owner: "房东",
    signed: "已签署",
    unsigned: "未签署",
    viewContract: "查看合同",
    viewAndSign: "查看并签署",
    roomDocuments: "房间文件",
    attachments: "合同附件",
    documentHint: "查看此合同的附件",
    noAttachments: "暂无合同附件",
    contractCount: "{count} 份合同",
    contractsHint: "在此查看合同副本和签署状态。",
    emptyContracts: "此账户尚未收到合同",
    emptyRoom: "此房间暂无合同",
    status: {
      draft: "草稿",
      awaiting_signatures: "等待签署",
      awaiting_agent_review: "等待审核",
      awaiting_payment: "等待付款",
      awaiting_payment_verification: "付款审核中",
      active: "已生效",
      cancelled: "已取消",
      expired: "已到期",
      terminated: "已终止",
    },
  },
  ja: {
    latest: "最新",
    paid: "支払い済み",
    billDetails: "請求詳細",
    currentBill: "現在の請求",
    billNo: "請求番号",
    billsList: "請求一覧",
    allBills: "すべて",
    unpaid: "未払い",
    pay: "支払い報告 / 明細を添付",
    reviewing: "確認中",
    copyAccount: "コピー",
    copied: "コピー済み",
    copyFailed: "口座番号をコピーできませんでした。もう一度お試しください。",
    room: "部屋",
    unitNo: "番号",
    noPaidBills: "支払い済みの請求はありません",
    noUnpaidBills: "未払いの請求はありません",
    noBills: "請求はまだありません",
    myContracts: "自分の契約",
    contractsAndTenants: "契約と入居者",
    ownerWorkspace: "オーナー",
    searchRooms: "部屋を検索",
    allRooms: "すべての部屋",
    waitingOnYou: "あなたの対応待ち",
    roomsWithContracts: "あなたの部屋",
    roomCount: "{count} 室",
    noLeaseHistory: "入居履歴はありません",
    leaseRounds: "履歴 {count} 回",
    pendingDocs: "未完了の書類 {count} 件",
    waitingYourSignature: "あなたの署名待ち",
    awaitingAgentSignature: "担当者の署名待ち",
    noActiveContract: "有効な契約はありません",
    renewalAction: "更新",
    clearSearch: "検索をクリア",
    noMatchingRooms: "一致する部屋がありません",
    roomHistory: "入居した部屋",
    leasedRooms: "貸していた部屋",
    emptyLeasedRooms: "貸していた部屋はまだありません",
    tenantHistory: "入居者の履歴",
    tenantHistoryHint: "名前を開いてその入居者の契約を確認",
    searchTenants: "入居者を検索",
    noMatchingTenants: "一致する入居者がいません",
    emptyTenantHistory: "入居者の履歴はまだありません",
    noCurrentTenant: "現在の入居者はいません",
    roomTenants: "この部屋に住んだ人",
    emptyRoomTenants: "この部屋の入居者はまだいません",
    peopleCount: "{count} 人",
    stayDates: "入居 {moveIn} · 退去 {moveOut}",
    roomHistoryHint: "部屋を開いて契約と書類を確認",
    billHistoryHint: "部屋を開いて請求を確認",
    paymentHistory: "支払い履歴",
    billCount: "請求 {count} 件",
    currentStay: "現在の入居",
    pastStay: "退去済み",
    emptyHistory: "入居した部屋はまだありません",
    currentContract: "現在の賃貸契約",
    nextRentBill: "次回の家賃請求",
    noMoreRentBills: "この契約の今後の家賃請求はありません",
    lease: "住宅賃貸契約",
    reservation: "予約書",
    broker: "仲介委任契約",
    contractNo: "契約番号",
    start: "開始日",
    end: "終了日",
    rent: "月額家賃",
    deposit: "敷金",
    tenant: "入居者",
    owner: "貸主",
    signed: "署名済み",
    unsigned: "未署名",
    viewContract: "契約を見る",
    viewAndSign: "確認して署名",
    roomDocuments: "部屋の書類",
    attachments: "契約添付書類",
    documentHint: "この契約の添付書類を見る",
    noAttachments: "契約添付書類はありません",
    contractCount: "契約 {count} 件",
    contractsHint: "契約の写しと署名状況をまとめて確認できます。",
    emptyContracts: "このアカウントに届いた契約はありません",
    emptyRoom: "この部屋の契約はありません",
    status: {
      draft: "下書き",
      awaiting_signatures: "署名待ち",
      awaiting_agent_review: "確認待ち",
      awaiting_payment: "支払い待ち",
      awaiting_payment_verification: "支払い確認中",
      active: "有効",
      cancelled: "キャンセル済み",
      expired: "期限切れ",
      terminated: "終了",
    },
  },
};

export function tenantWorkspaceCopy(locale: SupportedLocale) {
  return copy[locale];
}
