// Compares TypeORM entities with the database in `.env.api` and offers to apply the migrations that fix it.
// Usage: npm run db:check -w @nestyk/api [-- --check]   (--check: report only, never ask)
const path = require('node:path');
const fs = require('node:fs');
const readline = require('node:readline/promises');
const ts = require('typescript');
require('reflect-metadata');
require('dotenv').config({ path: path.resolve(__dirname, '../../../.env.api'), quiet: true });

require.extensions['.ts'] = (module, filename) => {
  const source = fs.readFileSync(filename, 'utf8');
  module._compile(ts.transpileModule(source, { compilerOptions: {
    module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022,
    experimentalDecorators: true, emitDecoratorMetadata: true, esModuleInterop: true,
  }, fileName: filename }).outputText, filename);
};

const { DataSource } = require('typeorm');
const { ALL_ENTITIES } = require('../src/entities/index.ts');
const {
  checkSchemaDrift,
  describeSchemaDrift,
  isSchemaDriftError,
  migrationsForDrift,
  uncoveredDrift,
} = require('../src/database/schema-drift.ts');

const MIGRATIONS_DIR = path.resolve(__dirname, '../migrations');
const color = (code) => (text) => (process.stdout.isTTY ? `\x1b[${code}m${text}\x1b[0m` : text);
const red = color(31);
const green = color(32);
const yellow = color(33);
const bold = color(1);

function loadMigrations() {
  return fs.readdirSync(MIGRATIONS_DIR)
    .filter((name) => name.endsWith('.sql'))
    .sort()
    .map((name) => ({ name, sql: fs.readFileSync(path.join(MIGRATIONS_DIR, name), 'utf8') }));
}

function quote(name) {
  return '"' + name.replace(/"/g, '""') + '"';
}

/** Hand-review SQL for drift no migration file covers; type/nullability changes are never auto-applied. */
function manualSql(issue) {
  if (issue.kind === 'type_mismatch') {
    return `ALTER TABLE ${quote(issue.table)} ALTER COLUMN ${quote(issue.column)} TYPE ${issue.expected} USING ${quote(issue.column)}::${issue.expected};`;
  }
  if (issue.kind === 'nullable_mismatch') {
    return `ALTER TABLE ${quote(issue.table)} ALTER COLUMN ${quote(issue.column)} ${issue.expected ? 'DROP' : 'SET'} NOT NULL;`;
  }
  return null;
}

/** Additive TypeORM SQL (CREATE TABLE / ADD column) for missing tables and columns no migration creates. */
async function generatedSql(dataSource, issues) {
  const missing = issues.filter((issue) => issue.kind === 'missing_table' || issue.kind === 'missing_column');
  if (!missing.length) return [];
  const { upQueries } = await dataSource.driver.createSchemaBuilder().log();
  const wanted = missing.map((issue) => issue.kind === 'missing_table'
    ? new RegExp(`^CREATE TABLE (?:"[^"]+"\\.)?${quote(issue.table)} `)
    : new RegExp(`^ALTER TABLE (?:"[^"]+"\\.)?${quote(issue.table)} ADD ${quote(issue.column)} `));
  return upQueries.map((q) => q.query).filter((query) => wanted.some((re) => re.test(query)));
}

function writeSyncMigration(queries) {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  let name = `${date}-schema-sync.sql`;
  for (let n = 2; fs.existsSync(path.join(MIGRATIONS_DIR, name)); n++) name = `${date}-schema-sync-${n}.sql`;
  const body = [
    '-- Generated by `npm run db:check` from TypeORM entities. Review (foreign keys, checks, indexes) before applying.',
    ...queries.map((query) => `${query};`),
    '',
  ].join('\n');
  fs.writeFileSync(path.join(MIGRATIONS_DIR, name), body);
  return name;
}

async function applyMigrations(dataSource, schema, files) {
  const runner = dataSource.createQueryRunner();
  await runner.connect();
  try {
    await runner.startTransaction();
    await runner.query("SET LOCAL lock_timeout = '5s'");
    await runner.query("SET LOCAL statement_timeout = '30s'");
    await runner.query('SELECT set_config($1, $2, true)', ['search_path', quote(schema)]);
    for (const name of files) {
      console.log(`  รัน ${name}`);
      await runner.query(fs.readFileSync(path.join(MIGRATIONS_DIR, name), 'utf8'));
    }
    await runner.commitTransaction();
  } catch (error) {
    await runner.rollbackTransaction();
    throw error;
  } finally {
    await runner.release();
  }
}

async function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    return /^y(es)?$/i.test((await rl.question(question)).trim());
  } finally {
    rl.close();
  }
}

async function report(dataSource, schema) {
  const issues = await checkSchemaDrift(dataSource, schema);
  const errors = issues.filter(isSchemaDriftError);
  for (const issue of issues.filter((issue) => !isSchemaDriftError(issue))) {
    console.log(yellow(`! ${describeSchemaDrift(issue)}`));
  }
  if (!errors.length) {
    console.log(green(`✓ entity ตรงกับฐานข้อมูล (${dataSource.entityMetadatas.length} ตาราง, schema "${schema}")`));
  } else {
    console.error(red(bold(`✗ entity กับฐานข้อมูลไม่ตรงกัน ${errors.length} จุด`)));
    for (const issue of errors) console.error(red(`  - ${describeSchemaDrift(issue)}`));
  }
  return errors;
}

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('ไม่พบ DATABASE_URL ใน .env.api');
  const schema = process.env.DB_SCHEMA || 'public';
  const interactive = process.stdin.isTTY && process.stdout.isTTY && !process.argv.includes('--check');
  const dataSource = new DataSource({
    type: 'postgres',
    url,
    schema,
    entities: ALL_ENTITIES,
    ssl: /localhost|127\.0\.0\.1/.test(url) ? false : { rejectUnauthorized: false },
  });
  await dataSource.initialize();
  try {
    const errors = await report(dataSource, schema);
    if (!errors.length) return;
    process.exitCode = 1;

    const migrations = loadMigrations();
    const files = migrationsForDrift(errors, migrations);
    const uncovered = uncoveredDrift(errors, migrations);
    const manual = uncovered.map(manualSql).filter(Boolean);
    const generated = await generatedSql(dataSource, uncovered);

    if (files.length) {
      console.log(`\nไฟล์ migration ที่สร้างสิ่งที่ขาด:`);
      for (const name of files) console.log(`  - migrations/${name}`);
    }
    if (generated.length) {
      console.log(`\nไม่มีไฟล์ migration สำหรับบางจุด จะสร้างไฟล์ใหม่จาก entity ให้ตรวจก่อนรัน (${generated.length} คำสั่ง)`);
    }
    if (manual.length) {
      console.log(yellow('\nจุดนี้อาจทำข้อมูลเสีย จะไม่ปรับให้อัตโนมัติ ตรวจแล้วรันเองถ้าต้องการ:'));
      for (const sql of manual) console.log(`  ${sql}`);
    }
    if (!files.length && !generated.length) return;
    if (!interactive) {
      console.log('\nรัน `npm run db:check -w @nestyk/api` ในเทอร์มินัลเพื่อเลือกปรับฐานข้อมูล');
      return;
    }

    if (!(await ask(bold('\nต้องการปรับฐานข้อมูลให้ตรงไหม? (y/N) ')))) {
      console.log('ยกเลิก ไม่ได้แก้ฐานข้อมูล');
      return;
    }
    if (generated.length) {
      const name = writeSyncMigration(generated);
      console.log(yellow(`สร้างไฟล์ migrations/${name} แล้ว ตรวจไฟล์แล้วรัน db:check อีกครั้งเพื่อนำไปใช้`));
    }
    if (files.length) {
      await applyMigrations(dataSource, schema, files);
      console.log(green('ปรับฐานข้อมูลแล้ว ตรวจซ้ำ:'));
      if (!(await report(dataSource, schema)).length) process.exitCode = 0;
    }
  } finally {
    await dataSource.destroy();
  }
}

main().catch((error) => {
  console.error(red(`ตรวจโครงสร้างฐานข้อมูลไม่สำเร็จ: ${error.code || error.message}`));
  process.exitCode = 1;
});
